const express=require('express')
const { addNewProduct, editProduct,sendOTP ,getOrderType,undoDeleteProduct,deleteProduct,changeStatus,getAllOrders,} = require('../Controllers/adminController')
const { isAuth, isAdmin } = require('../middlewares/auth')
const router=express.Router()
router.post('/add-new-product',isAuth,isAdmin,addNewProduct)
// router.get('/allHomeProduct',isAuth,isAdmin,getAllHomeProducts)
router.patch('/edit-product/:id',isAuth,isAdmin,editProduct)
router.post('/send-otp',sendOTP)
router.get('/all-orders',isAuth,isAdmin,getAllOrders)
router.get('/orderType',isAuth,isAdmin,getOrderType)
// router.get('/remaining-orders',isAuth,isAdmin,getRemainingOrders)
// router.get('/dispatched-orders',isAuth,isAdmin,getAllDispatchedOrders)
// router.get('/deliverdOrders',isAuth,isAdmin,getAllDeliveredOrders)
// router.get('/cancelledOrders',isAuth,isAdmin,getAllCancelledOrders)
router.post('/change-status',isAuth,isAdmin,changeStatus)
router.delete('/delete-product/:id',isAuth,isAdmin,deleteProduct)
router.delete('/undo-delete-product/:id',isAuth,isAdmin,undoDeleteProduct)
// router.get('/cancelledOrders',getAllCancelledOrders)
module.exports=router